export const typeOptions = [
  "Sunset/Sunrise",
  "Landscape",
  "Nature",
  "Water/Coastal",
  "Wildlife/Animals",
  "People/Portraits",
  "Architecture",
  "City/Urban",
  "Astrophotography",
  "Panoramic",
  "Transport (Cars,Trains)",
  "Weddings",
  "Abandoned",
];

export const equipmentOptions = [
  "Tripod",
  "Shutter Release Cable",
  "Filters",
  "Cleaning Equipment",
  "Rain Cover",
  "Flash/speedlight",
  "Flash Radio Triggers",
  "Light Modifiers",
  "Wide Angle Lens",
  "Telephoto Lens",
  "Prime Lens",
  "Macro Lens",
  "An Assistant",
];
